"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrintDataBoolEnum = exports.PathTypeEnum = exports.TypeEmissionEnum = exports.NFeModelEnum = exports.UFInitialsEnum = exports.UFCodeEnum = void 0;
var UFCodeEnum;
(function (UFCodeEnum) {
    UFCodeEnum[UFCodeEnum["AC"] = 12] = "AC";
    UFCodeEnum[UFCodeEnum["AL"] = 27] = "AL";
    UFCodeEnum[UFCodeEnum["AM"] = 13] = "AM";
    UFCodeEnum[UFCodeEnum["AP"] = 16] = "AP";
    UFCodeEnum[UFCodeEnum["BA"] = 29] = "BA";
    UFCodeEnum[UFCodeEnum["CE"] = 23] = "CE";
    UFCodeEnum[UFCodeEnum["DF"] = 53] = "DF";
    UFCodeEnum[UFCodeEnum["ES"] = 32] = "ES";
    UFCodeEnum[UFCodeEnum["GO"] = 52] = "GO";
    UFCodeEnum[UFCodeEnum["MA"] = 21] = "MA";
    UFCodeEnum[UFCodeEnum["MG"] = 31] = "MG";
    UFCodeEnum[UFCodeEnum["MS"] = 50] = "MS";
    UFCodeEnum[UFCodeEnum["MT"] = 51] = "MT";
    UFCodeEnum[UFCodeEnum["PA"] = 15] = "PA";
    UFCodeEnum[UFCodeEnum["PB"] = 25] = "PB";
    UFCodeEnum[UFCodeEnum["PE"] = 26] = "PE";
    UFCodeEnum[UFCodeEnum["PI"] = 22] = "PI";
    UFCodeEnum[UFCodeEnum["PR"] = 41] = "PR";
    UFCodeEnum[UFCodeEnum["RJ"] = 33] = "RJ";
    UFCodeEnum[UFCodeEnum["RN"] = 24] = "RN";
    UFCodeEnum[UFCodeEnum["RO"] = 11] = "RO";
    UFCodeEnum[UFCodeEnum["RR"] = 14] = "RR";
    UFCodeEnum[UFCodeEnum["RS"] = 43] = "RS";
    UFCodeEnum[UFCodeEnum["SC"] = 42] = "SC";
    UFCodeEnum[UFCodeEnum["SE"] = 28] = "SE";
    UFCodeEnum[UFCodeEnum["SP"] = 35] = "SP";
    UFCodeEnum[UFCodeEnum["TO"] = 17] = "TO";
})(UFCodeEnum = exports.UFCodeEnum || (exports.UFCodeEnum = {}));
var UFInitialsEnum;
(function (UFInitialsEnum) {
    UFInitialsEnum[UFInitialsEnum["AC"] = 0] = "AC";
    UFInitialsEnum[UFInitialsEnum["AL"] = 1] = "AL";
    UFInitialsEnum[UFInitialsEnum["AM"] = 2] = "AM";
    UFInitialsEnum[UFInitialsEnum["AP"] = 3] = "AP";
    UFInitialsEnum[UFInitialsEnum["BA"] = 4] = "BA";
    UFInitialsEnum[UFInitialsEnum["CE"] = 5] = "CE";
    UFInitialsEnum[UFInitialsEnum["DF"] = 6] = "DF";
    UFInitialsEnum[UFInitialsEnum["ES"] = 7] = "ES";
    UFInitialsEnum[UFInitialsEnum["GO"] = 8] = "GO";
    UFInitialsEnum[UFInitialsEnum["MA"] = 9] = "MA";
    UFInitialsEnum[UFInitialsEnum["MG"] = 10] = "MG";
    UFInitialsEnum[UFInitialsEnum["MS"] = 11] = "MS";
    UFInitialsEnum[UFInitialsEnum["MT"] = 12] = "MT";
    UFInitialsEnum[UFInitialsEnum["PA"] = 13] = "PA";
    UFInitialsEnum[UFInitialsEnum["PB"] = 14] = "PB";
    UFInitialsEnum[UFInitialsEnum["PE"] = 15] = "PE";
    UFInitialsEnum[UFInitialsEnum["PI"] = 16] = "PI";
    UFInitialsEnum[UFInitialsEnum["PR"] = 17] = "PR";
    UFInitialsEnum[UFInitialsEnum["RJ"] = 18] = "RJ";
    UFInitialsEnum[UFInitialsEnum["RN"] = 19] = "RN";
    UFInitialsEnum[UFInitialsEnum["RO"] = 20] = "RO";
    UFInitialsEnum[UFInitialsEnum["RR"] = 21] = "RR";
    UFInitialsEnum[UFInitialsEnum["RS"] = 22] = "RS";
    UFInitialsEnum[UFInitialsEnum["SC"] = 23] = "SC";
    UFInitialsEnum[UFInitialsEnum["SE"] = 24] = "SE";
    UFInitialsEnum[UFInitialsEnum["SP"] = 25] = "SP";
    UFInitialsEnum[UFInitialsEnum["TO"] = 26] = "TO";
})(UFInitialsEnum = exports.UFInitialsEnum || (exports.UFInitialsEnum = {}));
var NFeModelEnum;
(function (NFeModelEnum) {
    NFeModelEnum[NFeModelEnum["NFe"] = 55] = "NFe";
    NFeModelEnum[NFeModelEnum["NFCe"] = 65] = "NFCe";
})(NFeModelEnum = exports.NFeModelEnum || (exports.NFeModelEnum = {}));
var TypeEmissionEnum;
(function (TypeEmissionEnum) {
    TypeEmissionEnum[TypeEmissionEnum["teNormal"] = 1] = "teNormal";
    TypeEmissionEnum[TypeEmissionEnum["teContingency"] = 2] = "teContingency";
    TypeEmissionEnum[TypeEmissionEnum["teSCAN"] = 3] = "teSCAN";
    TypeEmissionEnum[TypeEmissionEnum["teDPEC"] = 4] = "teDPEC";
    TypeEmissionEnum[TypeEmissionEnum["teFSDA"] = 5] = "teFSDA";
    TypeEmissionEnum[TypeEmissionEnum["teSVCAN"] = 6] = "teSVCAN";
    TypeEmissionEnum[TypeEmissionEnum["teSVCRS"] = 7] = "teSVCRS";
    TypeEmissionEnum[TypeEmissionEnum["teSVCSP"] = 8] = "teSVCSP";
    TypeEmissionEnum[TypeEmissionEnum["teOffLine"] = 9] = "teOffLine";
})(TypeEmissionEnum = exports.TypeEmissionEnum || (exports.TypeEmissionEnum = {}));
var PathTypeEnum;
(function (PathTypeEnum) {
    PathTypeEnum[PathTypeEnum["NFe"] = 0] = "NFe";
    PathTypeEnum[PathTypeEnum["Unusable"] = 1] = "Unusable";
    PathTypeEnum[PathTypeEnum["CCe"] = 2] = "CCe";
    PathTypeEnum[PathTypeEnum["Cancellation"] = 3] = "Cancellation";
})(PathTypeEnum = exports.PathTypeEnum || (exports.PathTypeEnum = {}));
var PrintDataBoolEnum;
(function (PrintDataBoolEnum) {
    PrintDataBoolEnum["yes"] = "True";
    PrintDataBoolEnum["no"] = "False";
})(PrintDataBoolEnum = exports.PrintDataBoolEnum || (exports.PrintDataBoolEnum = {}));
